### ISSUE TITLE
Any known issues ?

### ISSUE THREAD

**Issue by ranshalit** [turboscrew/rpi_stub#1]
Hello,
I would please like to use with with another arm cortex a7 or a8.
As far as you know, is it stable and work without any issues ?

Thank you,
ranran

**Comment by turboscrew** [comment]
I don't know about the stability. Nobody has reported any bugs.
But it is Raspberry Pi 2/3 specific. It's bare metal, and the GPU connection plays a significant role.
Also the gebugger serial is written in register level.
